/*******************************************************************************

 * Copyright (c) 2016 Techurate Systems Pvt Ltd.
 *
 * All rights reserved.  No part of this work may be reproduced, stored in a retrieval system,
 * adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
 * graphic, optic recording or otherwise, translated in any language or computer language, without
 * the prior written permission of Techurate Systems Pvt Ltd.
 * Techurate Systems Pvt Ltd 
 * 227, 5th Main Rd, Indira Nagar II Stage,
 * Hoysala Nagar, Indiranagar, Bengaluru, 
 * Karnataka 560038, India
 *******************************************************************************/
package com.steel.product.application.util;

import org.springframework.util.StringUtils;

public interface ValidationConstants {

	public static final String ALPHA = "^[a-zA-Z ]*$";
	public static final String NUMBER = "^[0-9]*$";
	public static final String ALPHANUM = "^[a-zA-Z0-9 ]*$";
	public static final String NAME = "^[a-zA-Z0-9-_ ]*$";
	public static final String REMARKS = "^[a-zA-Z0-9_ ,.-]*$";
	public static final String ADDRESS = "^[a-zA-Z0-9_ ,#-]*$";
	public static final String MOBILE = "^[0-9+]*$";
	public static final String OTP = "^[0-9+]*$";
	public static final String USERNAME = "^[a-zA-ZÀ-ÿ0-9_@. -]*$";
	public static final String IPV4_PATTERN = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$";
	public static final String IPV6_STD_PATTERN = "^(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$";
	public static final String IPV6_HEX_COMPRESSED_PATTERN = "^((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)::((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)$";
	public static final String EMAIL = "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?";

	public enum TransferTypes {
		IAT, OAT, EAT, SAL, QPY, QPN, DDACC, RTGS, SWIFT;
	}

	public enum Currency {
		USD, GBP, ZAR, EUR, CHF, ZMK, ZWD, TZS, AUD, BWP, CAD, DKK, INR, KES, NOK, SEK, ZMW, MWK, JPY, TSH, NLG, ITL,
		FRF, DEM, BEF, DZD, AOA, ARS, ATS, BSD, BHD, BDT, AMD, BBD, BMD, BTN, BOB, BZD, SBD, BND, BGL, MMK, BIF, KHR,
		CVE, KYD, LKR, CLP, COP, KMF, CRC, HRK, CUP, CYP, CSK, CZK, DOP, ECS, SVC, GQE, ETB, ERN, EEK, FKP, FJD, FIM,
		DJF, GEK, GMD, GHC, GIP, GRD, GTQ, GNF, GYD, HTG, HNL, HKD, HUF, ISK, IDR, IRR, IRA, IQD, IEP, ILS, JMD, KZT,
		JOD, KPW, KRW, KWD, KGS, LAK, LBP, LSL, LVL, LRD, LYD, LTL, LUF, MOP, MGF, MYR, MVR, MTL, MRO, MUR, MXN, MNT,
		MDL, MAD, MZM, OMR, NAD, NPR, ANG, AWG, VUV, NZD, NIO, NGN, PKR, PAB, PGK, CNY, PYG, PEN, PHP, PLZ, PTE, GWP,
		TPE, QAR, RUB, RWF, SHP, STD, SAR, SCR, SLL, SGD, SKK, VND, SIT, SOS, YDD, ESP, SDD, SDA, SRG, SZL, SYP, THB,
		TOP, TTD, AED, TND, TMM, UGX, UAK, MKD, EGP, BYN, AFN, AZN, BAM, BGN, BRL, BYR, CDF, GEL, MGA, PLN, RON, RSD,
		SRD, TJS, TRY, TWD, UAH, UYU, UZS, VEB, WST, XAF, XCD, XEU, XOF, XPF, YER, YUN;
	}

	public enum DeliveryMode {
		ADDRESS, BRANCH;
	}

	public enum Favorites {
		Y, N;
	}

	public enum RolloverTypes {
		P, I, N;
	}

	public enum BeneficiaryType {
		THIRD_PARTY, INTERNATIONAL
	}

	public enum AutoRolloverFlag {
		Y, N,;
	}

	public enum BeneTypes {
		DDACC, IAT, INBK, RTGS;
	}

	public enum Terms {
		Y, N;
	}

	public enum ThirdParty {
		Y, N;
	}

	public enum Flag {
		Y, N;
	}

	public enum TransferTypeSi {
		INTERNAL, OTHER;
	}

	public enum GetImageFor {
		P, B;
	}

	public enum UserType {
		U;
	}

	public enum QuickLoginType {
		Y, N;
	}

	public enum IdRequest {
		REGISTUSERVRFY, REGISTUSER, MPINREGISTVERIFY, MPINREGISTCONFIRM, MPINRESETVERIFY, MPINRESETCONFIRM,
		ACCOUNTDETAILS, PASSWORDRESETVERIFY, PASSWORDRESETCONFIRM, ACCOUNTSUMMARY, MINISTATEMENT, FULLSTATEMENT,
		USERPROFILE, GETPROFILEIMAGE, CHANGEPASSWORD, CHANGEMPIN, DELETEPROFILEIMAGE, UPDATEPROFILEIMAGE, FTVERIFYIAT,
		FTCONFIRMIAT, FTVERIFYOAT, FTCONFIRMOAT, FTVERIFYDDACC, FTCONFIRMDDACC, FTVERIFYRTGS, FTCONFIRMRTGS,
		FTVERIFYSWIFT, FTCONFIRMSWIFT, OTHERBANKSLIST, FORGOTPASSVRFY, FORGOTPASSREQ, FORGOTUSERNAMEVERIFY,
		FORGOTUSERNAMECONFIRM, LOGIN, MPINLOGIN, GENERATEOTP, VERITFYOTP, RECEIPTDOWNLOAD, RECEIPTTXN, BENEVERIFI,
		ADDINTBENE, ADDOTHRBENE, GETALLBENE, REMOVEBENES, ADDFAVEBEN, MODIFYBENE, CHEQUEBOOK, CHEQUEBOOKCONFIRM,
		SIREQUEST, SIREQUESTCONFIRM, UPLOADUUSERPROFILE, PWDCRITERIA, GETALLBILLERS, STOPCHEQUEBOOK,
		STOPCHECKBOOKCONFIRM, ACCOUNTLOOKUP, BILLPAYMENT, FUNDTRANSFER, FUNDTRANSFERCONFIRM, CBSRATES, ACTIVATEBENE,
		GENERATEOTPFORBENEADD, OFFERS, GETBENEIMAGES, UPDATEBENEIMAGE, DELETEBENEIMAGE, GETSILIST, GETRTGSBANKCODES,
		GETCURRENCIES, GETBRANCHDETAILS, CHEQUESTATUS, CHEQUESTATUSCONFIRM, CHEQUEBOOKSTATUS, CHEQUEBOOKSTATUSCONFIRM,
		REDEEMTD, REDEEMTDCONFIRM, CREATETD, CREATETDCONFIRM, REPAYLOAN, REPAYLOANCONFIRM, CLOSESI, CLOSESICONFIRM,
		MOVETOOTHERS, MOVETOFAV, VERIFYDETAILS, CREATECUSTOMER, GETFAVTRANSFERS, DELETEFAVTRANSFER, CREATEACCOUNTVERIFY,
		CREATEACCOUNTCONFIRM, FEEDBACK, GETCOUNTRYCODES, GETPROVINCEDETAILS, GETACCOUNTCLASSDETAILS, BANKERCHEQUECREATE,
		BANKERCHECKCREATECONFIRM, TOPUPTD, TOPUPTDCONFIRM, FAQ, TERMS, CARDINFO, GETNOTIFICATIONS, LOANSCALCULATOR,
		DEPOSITSCALCULATOR, CREATESAVINGACCOUNT, CREATESAVINGACCOUNTCONFIRM, CARDLIST, CARDREQUEST, CARDOPERATION,
		CARDPRODUCTS, LOANREQUEST, GETTRANSFERTYPES, GETALLBANKS, GETPENDINGBILLS, GETSUBSCRIPTIONS, GETBILLQUOTE,
		BILLCOLLECTION, GETSCHOOLS, SCHOOLPAY, CARDLESSCASH, LASTNTRANSACTION, RECEIPT, TRANSACTIONSFORREPEAT,
		GETLATESTVERSIONDETAILS, VERIFYACTIVELINK, ADDBILLERBENE, FETCHBILLERBENE, DELETEBILLERBENE, CHANGECARDPIN,
		ENCRYPTEDPUBKEY, BLOCKCARD, MISCODE, STMBVERIFY, STMBCONFIRM, CARDLOADVERIFY, CARDLOADCONFIRM, GETCARDACCOUNTS,
		CARDLESSGENTOK, CARDLESSVIEWTOK, CARDLESSCANCELTOK, CARDLESSGENTOKVERIFY, DELETEBILLER, LOANACCOUNTSTATEMENT,
		DEPOSITACCOUNTSTATEMENT, BP_OTHER_BILLPAYMENT, ACCOUNTLINKVERIFY, ACCOUNTLINKCONFIRM, ACCOUNTDELINKVERIFY,
		ACCOUNTDELINKCONFIRM, GETALLOTHERPAYMENTSLIST, SERVICEREQUEST, ASSETLIABILITY, RDCREATE, REMARKLIST,
		BANKTOWALLETVERIFY, BANKTOWALLETCONFIRM, GETCOUNTRIES, GETSWIFTCODES, WALLETLIST, GETBUYCURRENCY,
		EMPDETFORCUSTONBOARD, CHECKCUSTBYUNIQUEID, CROSSCURRENCYRATES, CURRENCYLIST, FTCHARGE, ISMPINREGISTERED,
		UPLOADREGISTRATIONIMAGE, DOWNLOADREGISTRATIONIMAGE, ACCOUNTNICKNAME, TERMDEPOSITTENOR, APPVERSION, MT103MESSAGE,
		FORMATLIST, BISTATEMENT, GETBALANCES, BRANCH_LOCATION, ATM_LOCATION, AGENT_LOCATION, BENE_VERIFY,
		BENE_INCONFIRM, BENE_OTHVERIFY, BENE_OTCONFIRM, BENE_LIST, BENE_REMOVE, BENE_MODIFY, BENE_TRANTYPE, BENE_FAV,
		LOGOUT, BENE_SETIMG, BENE_IMGLIST, BENE_REMOVEIMG, BENE_ADDINTBEN, BENE_UPDATEINTBEN, BENE_REMOVEINTBEN,
		OWNACCTRANSFERCONFIRM, OWNACCTRANSFER, DEPOSITACCOUNTDETAILS, FEATURECHECK, REFRESHLOGIN, SCHOOLPAYMENTS,
		UTILITYPAYMENTS, DEBITCARD_VERIFY, DEBITCARD_CONFIRM, INSTITUTIONSLIST, STUDENTDETAILS, SCHOOLPAYMENTSVERIFY,
		UTILITIESLIST, CUSTOMERDETAILS, UTILITYPAYMENTSVERIFY, CARDLESS, TERMDEPOSITINTERESTRATES,
		CARDLESS_GENTOKEN_VER, CARDLESS_GENTOKEN, CARDLESS_VIEWTOKEN, CARDLESS_CANCELTOKEN, VIEW_SCHEDULED_TRANSFERS,
		CANCEL_SCHEDULED_TRANSFERS, GETTDPRODUTS, STOPCHEQUEREASONLIST, SCHEDULEPAYMENT_VIEW,
		SCHEDULEPAYMENT_CANCEL_VERIFY, SCHEDULEPAYMENT_CANCEL_CONFIRM,BLOCKDEBITCARD,
		FTVERIFYREGION,FTCONFIRMREGION,GETMISCODE,TRANSACTIONSEARCH;

	}

	public enum OperationType {
		LOGIN, REGISTRATIONPWD, FORGOTPWD, REGISTERMPIN, FORGOTMPIN, CHANGEPWD, CHANGEMPIN;
	}

	public enum Language {
		en, fr, km, zh;
	}

	public enum Channels {
		WEB, ANDROID, IOS, INTERNET, USSD, CORPORATE, RETAIL, CORPWEB, CORPANDROID, CORPIOS;
	}

	public enum RegistrationTypes {
		CIF, ACCOUNT;
	}

	public enum CardTypes {
		NEW, RENEWAL, REPLACEMENT;
	}

	public enum CardProducts {

		EASY_LIFE("EASY LIFE"), EASY_LIFE_PLUS("EASY LIFE PLUS"), EASY_LIFE_FLEX("EASY LIFE FLEX");

		private String displayName;

		CardProducts(String displayName) {
			this.displayName = displayName;
		}

		public String displayName() {
			return displayName;
		}

		@Override
		public String toString() {
			return displayName;
		}
	}

	public enum Reasons {

		GENERATE_NEW_PIN("FOUND LOST/STOLEN"), FOUNF_LRS_CARD("FOUND LOST/STOLEN CARD"), FORGOT_PIN("FORGOT PIN"),
		EXPINATTEMPTS("EXCEEDED PIN ATTEMPTS"), LRS_PIN("LOST/STOLEN PIN"), LOST("LOST"), STOLEN("STOLEN");

		private String displayName;

		Reasons(String displayName) {
			this.displayName = displayName;
		}

		public String displayName() {
			return displayName;
		}

		@Override
		public String toString() {
			return displayName;
		}
	}

	public enum RequestType {

		GENERATE_NEW_PIN("GENERATE NEW PIN"), BLOCK_CARD("BLOCK CARD"), RESET_PIN("RESET PIN"),
		UNBLOCK_CARD("UNBLOCK CARD");

		private String displayName;

		RequestType(String displayName) {
			this.displayName = displayName;
		}

		public String displayName() {
			return displayName;
		}

		@Override
		public String toString() {
			return displayName;
		}
	}

	public enum AccountTypes {
		S, D, L, ALL;
	}

	public enum CardRequestType {
		NEW, RENEWAL, REPLACEMENT;
	}

	public enum ZraTransaction {
		Custom, Domestic;
	}

	public static enum Module {
		
		FUNDTRANSFER, REGISTRATION, PASSWORDRESET, LINKACCOUNT, DELINKACCOUNT, MPINREGISTRATION, MPINPASSWORDRESET,
		BILLPAYMENT, STOPCHEQUEPAYMENT, CHEQUESTATUS, CHEQUEBOOKSTATUS, CHEQUEREQUEST, SCHEDULEDPAYMENTS,
		SCHEDULEDTRANSFERS, BENEFICIARYTRANSFER, BENEFICIARY, BANKTOWALLET, CASAACCOUNT, TERM_DEPOSITE,
		STANDINGINSTRUCTION, LOANREPAY, FORGOTUSERNAME, CARDLESSCASHOUT, GENERAL, DEBITCARD, LOGIN, 
		BLOCKDEBITCARD,LANGUAGEUPDATE;

	};

	public static enum ErrorType {
		BAD_REQUEST, INTERNAL_SERVER_ERROR
	};

	public static enum Status {
		Y, N, A, L, SUCCESS, FAIL, ACTIVE, PENDING, SUCCESSFUL
	};

	public enum ChargeBorneBy {

		BEN("BEN"), OUR("OUR"), SHA("SHA"), NULL("NULL");

		private String name;

		ChargeBorneBy(String name) {
			this.name = name;
		}

		public static Boolean isExist(String name) {

			if (StringUtils.isEmpty(name)) {
				return false;
			}

			for (ChargeBorneBy item : ChargeBorneBy.values()) {
				if (name.equalsIgnoreCase(item.name)) {
					return true;
				}
			}

			return false;
		}
	}
}
