package com.steel.product.jswone.request;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * One row of the SO Page Export = one jsw_sales_order_child line.
 * Field order matches template columns A..Y.
 */
@Data
public class SoPageExportDto {

	/** A - Sr. No. is generated by the writer, not carried here. */

	private String region;                       // B  <- so.branch_id
	private String orderId;                      // C  <- so.salesorder_id
	private String salesChannel;                 // D  <- so.bizsegment
	private String deliveryType;                 // E  <- so.deliverymethod
	private Date orderDate;                      // F  <- so.socreatedate
	private Integer deliveryTimeline;            // G  <- DATEDIFF(expected_delivery_date, socreatedate)
	private Date estimatedDeliveryDate;          // H  <- so.expected_delivery_date
	private String skuDescription;               // I  <- soc.material_name
	private BigDecimal orderQtySheets;           // J  <- soc.number_of_sheets (stored as varchar)
	private BigDecimal orderQtyMt;               // K  <- soc.soqty
	private BigDecimal invoicedQtyMt;            // L  <- see invoiced-qty subquery in the service
	private BigDecimal balanceQtyMt;             // M  <- orderQtyMt - invoicedQtyMt
	private String zohoStatusOfSo;               // N  <- so.zoho_status
	private String processingCentre;              // O  <- so.destinationcode
	private String allocatedCoil;                 // P  <- GROUP_CONCAT over jsw_sales_order_allocation
	private String packingMode;                   // Q  <- so.typeofsupply
	private String sdi;                           // R  <- so.special_delivery_instructions
	private Date likelyMaterialReadinessDate;     // S  <- so.likely_material_date
	private Date standardMaterialReadinessDate;   // T  <- so.standard_material_date
	private String wmsStatusOfSku;                 // U  <- soc.allocated_stts
	private String delayStatus;                    // V  derived from delayDays
	private String delayBucket;                    // W  derived from delayDays
	private String delayReason;                    // X  <- soc.special_instructions
	private String commentsForDelays;              // Y  <- so.remarks

	/** Not exported; drives the V/W derivation. */
	private Integer delayDays;
}
